export const mockCategories = [
  { _id: '1', name: 'Gạch Ốp Tường', slug: { current: 'gach-op-tuong' }, icon: '🧱', description: 'Gạch ốp tường đẹp, đa dạng mẫu mã' },
  { _id: '2', name: 'Gạch Lát Nền', slug: { current: 'gach-lat-nen' }, icon: '⬛', description: 'Gạch lát nền cao cấp, bền bỉ' },
  { _id: '3', name: 'Thiết Bị Vệ Sinh', slug: { current: 'thiet-bi-ve-sinh' }, icon: '🚿', description: 'Bồn cầu, lavabo, vòi sen cao cấp' },
  { _id: '4', name: 'Gạch Ngoại Thất', slug: { current: 'gach-ngoai-that' }, icon: '🏠', description: 'Gạch chịu lực, chống trơn ngoài trời' },
]

export const mockProducts = [
  {
    _id: 'p1',
    name: 'Gạch Marble Trắng Carrara 60x60',
    slug: { current: 'gach-marble-trang-carrara-60x60' },
    price: 850000,
    unit: 'm²',
    category: { name: 'Gạch Lát Nền', slug: { current: 'gach-lat-nen' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80' } }],
    isFeatured: true,
    inStock: true,
    shortDescription: 'Gạch vân đá hoa cương trắng Carrara cao cấp, phù hợp phòng khách và phòng tắm',
    sku: 'HH-MWC-6060',
  },
  {
    _id: 'p2',
    name: 'Gạch Ốp Tường Xám Nhạt 30x60',
    slug: { current: 'gach-op-tuong-xam-nhat-30x60' },
    price: 420000,
    unit: 'm²',
    category: { name: 'Gạch Ốp Tường', slug: { current: 'gach-op-tuong' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=600&q=80' } }],
    isFeatured: true,
    inStock: true,
    shortDescription: 'Gạch ốp tường màu xám nhạt tinh tế, tạo không gian hiện đại',
    sku: 'HH-WGR-3060',
  },
  {
    _id: 'p3',
    name: 'Bồn Cầu Thông Minh Cảm Ứng',
    slug: { current: 'bon-cau-thong-minh-cam-ung' },
    price: 12500000,
    unit: 'cái',
    category: { name: 'Thiết Bị Vệ Sinh', slug: { current: 'thiet-bi-ve-sinh' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80' } }],
    isFeatured: true,
    inStock: true,
    shortDescription: 'Bồn cầu cảm ứng thế hệ mới, tiết kiệm nước, vệ sinh tự động',
    sku: 'HH-TSW-001',
  },
  {
    _id: 'p4',
    name: 'Gạch Gỗ Teak Vàng 20x120',
    slug: { current: 'gach-go-teak-vang-20x120' },
    price: 680000,
    unit: 'm²',
    category: { name: 'Gạch Lát Nền', slug: { current: 'gach-lat-nen' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80' } }],
    isFeatured: true,
    inStock: true,
    shortDescription: 'Gạch vân gỗ teak vàng ấm áp, kích thước dài tạo cảm giác rộng rãi',
    sku: 'HH-WTK-20120',
  },
  {
    _id: 'p5',
    name: 'Lavabo Âm Bàn Oval Trắng',
    slug: { current: 'lavabo-am-ban-oval-trang' },
    price: 3200000,
    unit: 'cái',
    category: { name: 'Thiết Bị Vệ Sinh', slug: { current: 'thiet-bi-ve-sinh' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=600&q=80' } }],
    isFeatured: false,
    inStock: true,
    shortDescription: 'Lavabo âm bàn hình oval, sứ cao cấp, dễ vệ sinh',
    sku: 'HH-LBO-001',
  },
  {
    _id: 'p6',
    name: 'Gạch Terrazzo Xám Xanh 60x60',
    slug: { current: 'gach-terrazzo-xam-xanh-60x60' },
    price: 560000,
    unit: 'm²',
    category: { name: 'Gạch Lát Nền', slug: { current: 'gach-lat-nen' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80' } }],
    isFeatured: false,
    inStock: true,
    shortDescription: 'Gạch Terrazzo phong cách retro hiện đại, độc đáo và sang trọng',
    sku: 'HH-TZB-6060',
  },
  {
    _id: 'p7',
    name: 'Vòi Sen Cây Inox 304',
    slug: { current: 'voi-sen-cay-inox-304' },
    price: 4800000,
    unit: 'bộ',
    category: { name: 'Thiết Bị Vệ Sinh', slug: { current: 'thiet-bi-ve-sinh' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1620626011761-996317702782?w=600&q=80' } }],
    isFeatured: false,
    inStock: true,
    shortDescription: 'Vòi sen cây inox 304 chống gỉ, đầu sen điều chỉnh 3 chế độ',
    sku: 'HH-SHC-304',
  },
  {
    _id: 'p8',
    name: 'Gạch Ngoại Thất Chống Trơn 40x40',
    slug: { current: 'gach-ngoai-that-chong-tron-40x40' },
    price: 320000,
    unit: 'm²',
    category: { name: 'Gạch Ngoại Thất', slug: { current: 'gach-ngoai-that' } },
    images: [{ asset: { url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80' } }],
    isFeatured: false,
    inStock: true,
    shortDescription: 'Gạch ngoại thất chống trơn R11, chịu tải trọng cao, phù hợp sân vườn',
    sku: 'HH-EXT-4040',
  },
]
